### ISSUE TITLE
Tests are flaky

### ISSUE THREAD

**Issue by pboothe** [m-lab/go#65] opened 2019-10-01 21:45 UTC
`logx` fails when weird things happen with task scheduling on Travis.
`bqext` fails every now and then for reasons I have not investigated.

It's frustrating, and I wish the associated tests were more reliable.

**Comment by stephen-soltesz** [comment] 2019-10-30 20:56
Apparently caused by an upstream change to error string contents in `bigquery` package for the bqfake_test errors.

The memoryless_test errors due to a race in the unit test.

Fixed by https://github.com/m-lab/go/pull/69

**Closed** 2019-10-30 20:56 UTC
Labels: P2, backlog, sre/review

**Comment by stephen-soltesz** [comment] 2019-11-04 21:21
https://github.com/m-lab/go/pull/72
